### ISSUE TITLE
Add the ability to complete from spell dictionaries

### ISSUE THREAD

**Issue by Shatur** [htlsne/asyncomplete-look#1]
Hello! Thank you for your plugin.
Is it possible to add the ability to autocomplete words from spell dictionaries as it implemented in [MUcomplete](https://github.com/lifepillar/vim-mucomplete)?

**Comment by hiterm** [comment]
Hello! Please try this branch and setting.
https://github.com/htlsne/asyncomplete-look/tree/spell.

```
au User asyncomplete_setup call asyncomplete#register_source({
    \ 'name': 'spell',
    \ 'whitelist': ['text', 'markdown'],
    \ 'completor': function('asyncomplete#sources#spell#completor'),
    \ })

" if you not set it other way
set spell
```

I think it is the same completion mechanism as MUcomplete (although I have never used that plugin).

**Comment by hiterm** [comment]
Maybe better experience with fuzzy filter such as [machakann/asyncomplete-ezfilter.vim](https://github.com/machakann/asyncomplete-ezfilter.vim).

```
let g:asyncomplete_preprocessor =
  \ [function('asyncomplete#preprocessor#ezfilter#filter')]

let g:asyncomplete#preprocessor#ezfilter#config = {}
let g:asyncomplete#preprocessor#ezfilter#config.spell =
  \ {ctx, items -> ctx.osa_filter(items, 1)}
```

**Comment by Shatur** [comment]
Yes, it works, thank you!
Is it possible to add information about completion source? For example, if I use completion from [buffer](https://github.com/prabirshrestha/asyncomplete-buffer.vim), it shows `[buffer]` to the right of the proposed word:
![изображение](https://user-images.githubusercontent.com/22453358/76141870-cc650e80-6070-11ea-950c-92a167f05504.png)
Something like `[spell]` or `[dictionary]`?

> Maybe better experience with fuzzy filter such as machakann/asyncomplete-ezfilter.vim.

Thank you, I like it :)

**Comment by hiterm** [comment]
Merged into master.

Added in latest version:

> Is it possible to add information about completion source? For example, if I use completion from buffer, it shows [buffer] to the right of the proposed word:
Something like [spell] or [dictionary]?

**Comment by Shatur** [comment]
Thank you a lot!

**Comment by Shatur** [comment]
Your plugin is very useful! I suggest to add this information to the repo readme and submit this plugin to the [asyncomplete sources](https://github.com/prabirshrestha/asyncomplete.vim#sources) too.

**Comment by Shatur** [comment]
After a long use, I began to notice that when using [machakann/asyncomplete-ezfilter.vim](https://github.com/machakann/asyncomplete-ezfilter.vim), Vim starts to work much slower, especially when moving the cursor. Now I use your plugin without it.

**Comment by Shatur** [comment]
I was wrong. The problem is in spell completion itself. Input response becomes much slower with it :(
This is especially noticeable when quickly entering a large number of characters. Try entering something like`ajsdashdkjahdkjahdkjahskdhakjhsdkjahsdhlkljkl`, you will see how your cursor hangs.

I understand that this, most likely, cannot be done faster :(

**Comment by hiterm** [comment]
I hear that `spellsuggest()` is slow.
For provide complete from spell dictionaries, another approach may be preferable.

Try this branch. It `grep` your dictionary file directly.
https://github.com/htlsne/asyncomplete-look/tree/grep

```
au User asyncomplete_setup call asyncomplete#register_source({
    \ 'name': 'look',
    \ 'whitelist': ['text', 'markdown'],
    \ 'completor': function('asyncomplete#sources#look#completor'),
    \ })

" Find your dictionary path such as /home/<username>/.vim/spell/en.utf-8.add
let g:asc_look_spell_file = /full/path/to/your/en.utf-8.add

au User asyncomplete_setup call asyncomplete#register_source({
    \ 'name': 'spell',
    \ 'whitelist': ['text', 'markdown'],
    \ 'completor': function('asyncomplete#sources#spell#completor'),
    \ })
```

**Comment by Shatur** [comment]
Sorry for newbie questions, but where can I find `en.utf-8.add` file? I using Neovim and have only preinstalled `/usr/share/nvim/runtime/spell/en.utf-8.spl` and `~/.local/share/nvim/site/spell/ru.utf-8.spl`. I tried both, but completion not works.

**Comment by hiterm** [comment]
Does `~/.config/nvim/spell/en.utf-8.add` exists? `.add` file is plain text file that contains your spell dictionary word.

**Comment by Shatur** [comment]
No, the `spell` directory even not exists.

**Comment by hiterm** [comment]
Hmm... When you use `zg` to add a good word, a message like `Word 'xxx' added to ~/.config/nvim/spell/en.utf-8.add` should be shown. This is `.add` file.

**Comment by Shatur** [comment]
Oh, sorry, I just didn’t add the words :)
I tested it with the following configuration:
```
au User asyncomplete_setup call asyncomplete#register_source({
    \ 'name': 'look',
    \ 'whitelist': ['text', 'markdown'],
    \ 'completor': function('asyncomplete#sources#look#completor'),
    \ })

let g:asc_look_spell_file = '/home/gena/.config/nvim/spell/en.utf-8.add'

au User asyncomplete_setup call asyncomplete#register_source({
    \ 'name': 'spell',
    \ 'whitelist': ['text', 'markdown'],
    \ 'completor': function('asyncomplete#sources#spell#completor'),
    \ })
```
But it not works, added word `plugins` not suggested. The file `/home/gena/.config/nvim/spell/en.utf-8.add` exists and contains `plugins`.

**Comment by hiterm** [comment]
> Oh, sorry, I just didn’t add the words :)

I thought "spell dictionaries" means these added words, didn't you mean that...?

> But it not works, added word plugins not suggested. The file /home/gena/.config/nvim/spell/en.utf-8.add exists and contains plugins.

Using `grep` branch, and editing filetype=text or markdown file?

**Comment by Shatur** [comment]
> I thought "spell dictionaries" means these added words, didn't you mean that...?

I meant auto-completion from the words that I added + words from the standard spell dictionary. The current `master` branch works in this way.

> Using grep branch, and editing filetype=text or markdown file?

Yes, I even checked on both filetypes.

**Comment by hiterm** [comment]
> I meant auto-completion from the words that I added + words from the standard spell dictionary. The current master branch works in this way.

If you mean "standard spell dictionary" is same dictionary as `z=`, all I can do now is current master branch.

`grep` branch uses your added words + `look` command dictionary (/usr/share/dict/words). I expect this is faster than master branch (not certainly because speed depends on environments).
It works like this.
![Screenshot from 2020-03-12 08-15-11](https://user-images.githubusercontent.com/6134287/76474349-b7a4c400-643e-11ea-9b8b-78b9370138e8.png)


If you don't like this, I don't have any other idea, sorry. If you like it, I can support to work this.

**Comment by Shatur** [comment]
> If you mean "standard spell dictionary" is same dictionary as z=, all I can do now is current master branch.

Yes, I understand :(
Maybe is it possible to add small completion delay to reduce input lag?

> grep branch uses your added words + look command dictionary (/usr/share/dict/words). I expect this is faster than master branch (not certainly because speed depends on environments).
It works like this.

Yes, this is nice idea. The `spellsuggest()` is better, but it's slow when I typing a lot of letters :(

**Comment by hiterm** [comment]
>  Maybe is it possible to add small completion delay to reduce input lag?

Sorry, I don't know how to implement it.

Now I decided to support only `grep` way because I think it is suitable for this plugin. I have already merged into master.
Please be careful that necessary setting changed from the above comment (https://github.com/htlsne/asyncomplete-look/issues/1#issuecomment-597591460).
